const getMathematicalOperation = (result) => {
  return {
    Rad: '',
    Deg: '',
    'x!': '',
    '(': '(',
    ')': ')',
    '%': '%',
    AC: '',
    Inv: '',
    7: 7,
    8: 8,
    9: 9,
    '/': '/',
    Pi: Math.PI,
    4: 4,
    5: 5,
    6: 6,
    '*': '*',
    e: Math.E,
    1: 1,
    2: 2,
    3: 3,
    '-': '-',
    Ans: '',
    0: 0,
    '.': '.',
    '=': '',
    '+': '+',
    sin: 'Math.sin(',
    Ln: 'Math.log(',
    cos: 'Math.cos(',
    log: 'Math.log10(',
    tan: 'Math.tan(',
    sqrt: 'Math.sqrt(',
    EXP: 'Math.exp(',
  };
};

export default getMathematicalOperation;
